apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reports-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: reports
    spec:
      containers:
      - name: reports
        image: quay.io/sevii/ll-report:latest
        ports:
        - containerPort: 8055
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: HTTP_PROXY
            value: "l5d:4140"

---
apiVersion: v1
kind: Service
metadata:
  name: reports
  labels:
    group: demo
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8055
    - name: external
      port: 80
      targetPort: 8055
  selector:
    app: reports